; Auto-generated. Do not edit!


(cl:in-package mastering_ros_demo_pkg-msg)


;//! \htmlinclude demo_actionFeedback.msg.html

(cl:defclass <demo_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((current_count
    :reader current_count
    :initarg :current_count
    :type cl:integer
    :initform 0))
)

(cl:defclass demo_actionFeedback (<demo_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <demo_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'demo_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mastering_ros_demo_pkg-msg:<demo_actionFeedback> is deprecated: use mastering_ros_demo_pkg-msg:demo_actionFeedback instead.")))

(cl:ensure-generic-function 'current_count-val :lambda-list '(m))
(cl:defmethod current_count-val ((m <demo_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mastering_ros_demo_pkg-msg:current_count-val is deprecated.  Use mastering_ros_demo_pkg-msg:current_count instead.")
  (current_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <demo_actionFeedback>) ostream)
  "Serializes a message object of type '<demo_actionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current_count)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <demo_actionFeedback>) istream)
  "Deserializes a message object of type '<demo_actionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_count) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<demo_actionFeedback>)))
  "Returns string type for a message object of type '<demo_actionFeedback>"
  "mastering_ros_demo_pkg/demo_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'demo_actionFeedback)))
  "Returns string type for a message object of type 'demo_actionFeedback"
  "mastering_ros_demo_pkg/demo_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<demo_actionFeedback>)))
  "Returns md5sum for a message object of type '<demo_actionFeedback>"
  "f77169e65b5b24a984cd3f9acb1e49b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'demo_actionFeedback)))
  "Returns md5sum for a message object of type 'demo_actionFeedback"
  "f77169e65b5b24a984cd3f9acb1e49b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<demo_actionFeedback>)))
  "Returns full string definition for message of type '<demo_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%int32 current_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'demo_actionFeedback)))
  "Returns full string definition for message of type 'demo_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%int32 current_count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <demo_actionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <demo_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'demo_actionFeedback
    (cl:cons ':current_count (current_count msg))
))
