// Generated by gencpp from file mastering_ros_demo_pkg/demo_actionResult.msg
// DO NOT EDIT!


#ifndef MASTERING_ROS_DEMO_PKG_MESSAGE_DEMO_ACTIONRESULT_H
#define MASTERING_ROS_DEMO_PKG_MESSAGE_DEMO_ACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mastering_ros_demo_pkg
{
template <class ContainerAllocator>
struct demo_actionResult_
{
  typedef demo_actionResult_<ContainerAllocator> Type;

  demo_actionResult_()
    : final_count(0)  {
    }
  demo_actionResult_(const ContainerAllocator& _alloc)
    : final_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _final_count_type;
  _final_count_type final_count;





  typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> const> ConstPtr;

}; // struct demo_actionResult_

typedef ::mastering_ros_demo_pkg::demo_actionResult_<std::allocator<void> > demo_actionResult;

typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionResult > demo_actionResultPtr;
typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionResult const> demo_actionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator1> & lhs, const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator2> & rhs)
{
  return lhs.final_count == rhs.final_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator1> & lhs, const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mastering_ros_demo_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaae876f57686d9f2a92f60bfbd26c85";
  }

  static const char* value(const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaae876f57686d9fULL;
  static const uint64_t static_value2 = 0x2a92f60bfbd26c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mastering_ros_demo_pkg/demo_actionResult";
  }

  static const char* value(const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 final_count\n"
;
  }

  static const char* value(const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demo_actionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mastering_ros_demo_pkg::demo_actionResult_<ContainerAllocator>& v)
  {
    s << indent << "final_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.final_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTERING_ROS_DEMO_PKG_MESSAGE_DEMO_ACTIONRESULT_H
