// Generated by gencpp from file mastering_ros_demo_pkg/demo_actionFeedback.msg
// DO NOT EDIT!


#ifndef MASTERING_ROS_DEMO_PKG_MESSAGE_DEMO_ACTIONFEEDBACK_H
#define MASTERING_ROS_DEMO_PKG_MESSAGE_DEMO_ACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mastering_ros_demo_pkg
{
template <class ContainerAllocator>
struct demo_actionFeedback_
{
  typedef demo_actionFeedback_<ContainerAllocator> Type;

  demo_actionFeedback_()
    : current_count(0)  {
    }
  demo_actionFeedback_(const ContainerAllocator& _alloc)
    : current_count(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_count_type;
  _current_count_type current_count;





  typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct demo_actionFeedback_

typedef ::mastering_ros_demo_pkg::demo_actionFeedback_<std::allocator<void> > demo_actionFeedback;

typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionFeedback > demo_actionFeedbackPtr;
typedef boost::shared_ptr< ::mastering_ros_demo_pkg::demo_actionFeedback const> demo_actionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator1> & lhs, const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_count == rhs.current_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator1> & lhs, const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mastering_ros_demo_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f77169e65b5b24a984cd3f9acb1e49b5";
  }

  static const char* value(const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf77169e65b5b24a9ULL;
  static const uint64_t static_value2 = 0x84cd3f9acb1e49b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mastering_ros_demo_pkg/demo_actionFeedback";
  }

  static const char* value(const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback definition\n"
"int32 current_count\n"
;
  }

  static const char* value(const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct demo_actionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mastering_ros_demo_pkg::demo_actionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTERING_ROS_DEMO_PKG_MESSAGE_DEMO_ACTIONFEEDBACK_H
